// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwWuUjtZgEZnxoXVsQbhqcgrEmrnmACgY',
    appId: '1:148076980089:web:1e3f99cc904488feab31a8',
    messagingSenderId: '148076980089',
    projectId: 'familyarchive-01',
    authDomain: 'familyarchive-01.firebaseapp.com',
    storageBucket: 'familyarchive-01.appspot.com',
    measurementId: 'G-J5R1G3G7RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MM79gyZwS5HqDkCS62SlivC1yf9Sm40',
    appId: '1:148076980089:android:41e5435477987a8eab31a8',
    messagingSenderId: '148076980089',
    projectId: 'familyarchive-01',
    storageBucket: 'familyarchive-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmpaDlEF7_jBIho2QGBSOWWERNujSdqlU',
    appId: '1:148076980089:ios:b3e524bd342724f6ab31a8',
    messagingSenderId: '148076980089',
    projectId: 'familyarchive-01',
    storageBucket: 'familyarchive-01.appspot.com',
    iosBundleId: 'com.mlb.mlbFamilyArchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmpaDlEF7_jBIho2QGBSOWWERNujSdqlU',
    appId: '1:148076980089:ios:a8f38243ecba9eebab31a8',
    messagingSenderId: '148076980089',
    projectId: 'familyarchive-01',
    storageBucket: 'familyarchive-01.appspot.com',
    iosBundleId: 'com.mlb.mlbFamilyArchive.RunnerTests',
  );
}
